// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyWarehouse.Data;

#nullable disable

namespace PharmacyWarehouse.Migrations
{
    [DbContext(typeof(PharmacyWarehouseContext))]
    [Migration("20260605101824_AddInventoryAndStorageTemp")]
    partial class AddInventoryAndStorageTemp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyWarehouse.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ArrivalDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int?>("IncomingDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sgtin")
                        .HasMaxLength(27)
                        .HasColumnType("nvarchar(27)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Партии__3214EC27A3B57D1D");

                    b.HasIndex(new[] { "IncomingDocumentId" }, "IX_Batches_IncomingDocumentId");

                    b.HasIndex(new[] { "ProductId" }, "IX_Batches_ProductId");

                    b.HasIndex(new[] { "SupplierId" }, "IX_Batches_SupplierId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.BatchCorrectionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CorrectionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CorrectionDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_BatchCorrectionLogs");

                    b.HasIndex(new[] { "BatchId" }, "IX_BatchCorrectionLogs_BatchId");

                    b.HasIndex(new[] { "CorrectionDocumentId" }, "IX_BatchCorrectionLogs_CorrectionDocumentId");

                    b.ToTable("BatchCorrectionLogs");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Категории__3214EC278AD91EA3");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValueSql("((0.0))");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CorrectionType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerDocument")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OriginalDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SupplierInvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupplierInvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WriteOffCommission")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WriteOffReason")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Документы__3214EC278A955341");

                    b.HasIndex(new[] { "OriginalDocumentId" }, "IX_Documents_OriginalDocumentId");

                    b.HasIndex(new[] { "SupplierId" }, "IX_Documents_SupplierId");

                    b.HasIndex(new[] { "Number" }, "UQ_Documents_Number")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.DocumentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CreatedBatchId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("NewValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("SellingPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SourceBatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Строки_документов__3214EC2788683C48");

                    b.HasIndex(new[] { "CreatedBatchId" }, "IX_DocumentLines_CreatedBatchId");

                    b.HasIndex(new[] { "DocumentId" }, "IX_DocumentLines_DocumentId");

                    b.HasIndex(new[] { "ProductId" }, "IX_DocumentLines_ProductId");

                    b.HasIndex(new[] { "SourceBatchId" }, "IX_DocumentLines_SourceBatchId");

                    b.ToTable("DocumentLines");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("InventoryDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.InventoryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualQuantity")
                        .HasColumnType("int");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryLines");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.MdlpDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MdlpDocumentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RequestXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("SchemaVersion")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ticket")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id")
                        .HasName("PK_MdlpDocuments");

                    b.HasIndex("DocumentId");

                    b.ToTable("MdlpDocuments");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.MdlpDocumentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MdlpDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MdlpDocumentId" }, "IX_MdlpDocumentHistory_MdlpDocumentId");

                    b.ToTable("MdlpDocumentHistory", (string)null);
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.MdlpSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("OrgInn")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("OrgName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SimulatedDelaySeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("SimulatedErrorRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("SubjectId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("UseMock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK_MdlpSettings");

                    b.ToTable("MdlpSettings");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.MdlpSgtin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MdlpDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sgtin")
                        .IsRequired()
                        .HasMaxLength(27)
                        .HasColumnType("nvarchar(27)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("InStock");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_MdlpSgtins");

                    b.HasIndex("BatchId");

                    b.HasIndex("MdlpDocumentId");

                    b.HasIndex(new[] { "Sgtin" }, "UQ_MdlpSgtins_Sgtin")
                        .IsUnique();

                    b.ToTable("MdlpSgtins");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchiveComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ArchiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSalesBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MinRemainder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReleaseForm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("bit");

                    b.Property<string>("StorageConditions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("StorageTemperatureMax")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal?>("StorageTemperatureMin")
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("шт.");

                    b.HasKey("Id")
                        .HasName("PK__Товары__3214EC2788EA4D93");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Products_CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Поставщики__3214EC2715F63432");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex(new[] { "Login" }, "IX_Users_Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Batch", b =>
                {
                    b.HasOne("PharmacyWarehouse.Models.Document", "IncomingDocument")
                        .WithMany("Batches")
                        .HasForeignKey("IncomingDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Batches_IncomingDocumentId");

                    b.HasOne("PharmacyWarehouse.Models.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Batches_ProductId");

                    b.HasOne("PharmacyWarehouse.Models.Supplier", "Supplier")
                        .WithMany("Batches")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_Batches_SupplierId");

                    b.Navigation("IncomingDocument");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.BatchCorrectionLog", b =>
                {
                    b.HasOne("PharmacyWarehouse.Models.Batch", "Batch")
                        .WithMany("BatchCorrectionLogs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BatchCorrectionLogs_BatchId");

                    b.HasOne("PharmacyWarehouse.Models.Document", "CorrectionDocument")
                        .WithMany("BatchCorrectionLogs")
                        .HasForeignKey("CorrectionDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BatchCorrectionLogs_CorrectionDocumentId");

                    b.Navigation("Batch");

                    b.Navigation("CorrectionDocument");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Document", b =>
                {
                    b.HasOne("PharmacyWarehouse.Models.Document", "OriginalDocument")
                        .WithMany("InverseOriginalDocument")
                        .HasForeignKey("OriginalDocumentId")
                        .HasConstraintName("FK_Documents_OriginalDocumentId");

                    b.HasOne("PharmacyWarehouse.Models.Supplier", "Supplier")
                        .WithMany("Documents")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Documents_SupplierId");

                    b.Navigation("OriginalDocument");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.DocumentLine", b =>
                {
                    b.HasOne("PharmacyWarehouse.Models.Batch", "CreatedBatch")
                        .WithMany("DocumentLineCreatedBatches")
                        .HasForeignKey("CreatedBatchId")
                        .HasConstraintName("FK_DocumentLines_CreatedBatchId");

                    b.HasOne("PharmacyWarehouse.Models.Document", "Document")
                        .WithMany("DocumentLines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentLines_DocumentId");

                    b.HasOne("PharmacyWarehouse.Models.Product", "Product")
                        .WithMany("DocumentLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_DocumentLines_ProductId");

                    b.HasOne("PharmacyWarehouse.Models.Batch", "SourceBatch")
                        .WithMany("DocumentLineSourceBatches")
                        .HasForeignKey("SourceBatchId")
                        .HasConstraintName("FK_DocumentLines_SourceBatchId");

                    b.Navigation("CreatedBatch");

                    b.Navigation("Document");

                    b.Navigation("Product");

                    b.Navigation("SourceBatch");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.InventoryLine", b =>
                {
                    b.HasOne("PharmacyWarehouse.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .IsRequired();

                    b.HasOne("PharmacyWarehouse.Models.Inventory", "Inventory")
                        .WithMany("InventoryLines")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.MdlpDocument", b =>
                {
                    b.HasOne("PharmacyWarehouse.Models.Document", "Document")
                        .WithMany("MdlpDocuments")
                        .HasForeignKey("DocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_MdlpDocuments_DocumentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.MdlpDocumentHistory", b =>
                {
                    b.HasOne("PharmacyWarehouse.Models.MdlpDocument", "MdlpDocument")
                        .WithMany("MdlpDocumentHistories")
                        .HasForeignKey("MdlpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MdlpDocumentHistory_MdlpDocumentId");

                    b.Navigation("MdlpDocument");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.MdlpSgtin", b =>
                {
                    b.HasOne("PharmacyWarehouse.Models.Batch", "Batch")
                        .WithMany("MdlpSgtins")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK_MdlpSgtins_BatchId");

                    b.HasOne("PharmacyWarehouse.Models.MdlpDocument", "MdlpDocument")
                        .WithMany("MdlpSgtins")
                        .HasForeignKey("MdlpDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_MdlpSgtins_MdlpDocumentId");

                    b.Navigation("Batch");

                    b.Navigation("MdlpDocument");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Product", b =>
                {
                    b.HasOne("PharmacyWarehouse.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Products_CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Batch", b =>
                {
                    b.Navigation("BatchCorrectionLogs");

                    b.Navigation("DocumentLineCreatedBatches");

                    b.Navigation("DocumentLineSourceBatches");

                    b.Navigation("MdlpSgtins");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Document", b =>
                {
                    b.Navigation("BatchCorrectionLogs");

                    b.Navigation("Batches");

                    b.Navigation("DocumentLines");

                    b.Navigation("InverseOriginalDocument");

                    b.Navigation("MdlpDocuments");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Inventory", b =>
                {
                    b.Navigation("InventoryLines");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.MdlpDocument", b =>
                {
                    b.Navigation("MdlpDocumentHistories");

                    b.Navigation("MdlpSgtins");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Product", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("DocumentLines");
                });

            modelBuilder.Entity("PharmacyWarehouse.Models.Supplier", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
